export const SIGN_IN_STARTED = 'SIGN_IN_STARTED';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL';
export const SAVE_USER_TOKEN = 'SAVE_USER_TOKEN';
export const SAVE_USER = 'SAVE_USER';

export const SIGN_UP_STARTED = 'SIGN_UP_STARTED';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';

export const SIGN_OUT_STARTED = 'SIGN_OUT_STARTED';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAIL = 'SIGN_OUT_FAIL';

export const FETCH_HABITS_STARTED = 'FETCH_HABITS_STARTED';
export const FETCH_HABITS_SUCCESS = 'FETCH_HABITS_SUCCESS';
export const FETCH_HABITS_FAIL = 'FETCH_HABITS_FAIL';

export const EDIT_HABIT_STARTED = 'EDIT_HABIT_STARTED';
export const EDIT_HABIT_SUCCESS = 'EDIT_HABIT_SUCCESS';
export const EDIT_HABIT_FAIL = 'EDIT_HABIT_FAIL';
export const EDIT_HABIT = 'EDIT_HABIT';

export const REFRESH_HABITS = 'REFRESH_HABITS';
export const REFRESH_COMPLETED_HABITS = 'REFRESH_COMPLETED_HABITS';

export const REFRESH_CATEGORIES = 'REFRESH_CATEGORIES';
